name: example
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  wayland:
    path: ../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
