name: wayland
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  xml: ^6.5.0
  args: ^2.5.0
  http: ^1.2.1
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

executables:
  wayland-scanner: scanner